let data = {
    station:[
        {stationNumber:'1000',stationName:'臺北'},
        {stationNumber:'0990',stationName:'松山'},
        {stationNumber:'1010',stationName:'萬華'},
        {stationNumber:'1020',stationName:'板橋'},
        {stationNumber:'4400',stationName:'高雄'},
        {stationNumber:'0900', stationName:'基隆'},
        {stationNumber:'0910', stationName:'三坑'},
        {stationNumber:'0920', stationName:'八堵'},
        {stationNumber:'0930', stationName:'七堵'},
        {stationNumber:'0940', stationName:'百福'},
        {stationNumber:'0950', stationName: '五堵'},
        {stationNumber:'0960', stationName: '汐止'},
        {stationNumber:'0970', stationName: '汐科'},
        {stationNumber:'0980', stationName: '南港'},
        {stationNumber:'0990', stationName: '松山'},
        {stationNumber: '1030', stationName: '浮洲'},
        {stationNumber: '1040', stationName: '樹林'},
        {stationNumber: '1050', stationName: '南樹林'},
        {stationNumber: '1060', stationName: '山佳'},
        {stationNumber: '1070', stationName: '鶯歌'},
        {stationNumber: '1080', stationName: '桃園'},
        {stationNumber: '1090', stationName: '內壢'},
        {stationNumber: '1100', stationName: '中壢'},
        {stationNumber: '1110', stationName: '埔心'},
        {stationNumber: '1120', stationName: '楊梅'},
        {stationNumber: '1130', stationName: '富岡'},
        {stationNumber: '1140', stationName: '新富'},
        {stationNumber: '1150', stationName: '北湖'},
        {stationNumber: '1160', stationName: '湖口'},
        {stationNumber: '1170', stationName: '新豐'},
        {stationNumber: '1180', stationName: '竹北'},
        {stationNumber: '1190', stationName: '北新竹'},
        {stationNumber: '1191', stationName: '千甲'},
        {stationNumber: '1192', stationName: '新莊'},
        {stationNumber: '1193', stationName: '竹中'},
        {stationNumber: '1194', stationName: '六家'},
        {stationNumber: '1201', stationName: '上員'},
        {stationNumber: '1202', stationName: '榮華'},
        {stationNumber: '1203', stationName: '竹東'},
        {stationNumber: '1204', stationName: '橫山'},
        {stationNumber: '1205', stationName: '九讚頭'},
        {stationNumber: '1206', stationName: '合興'},
        {stationNumber: '1207', stationName: '富貴'},
        {stationNumber: '1208', stationName: '內灣'},
        {stationNumber: '1210', stationName: '新竹'},
        {stationNumber: '1220', stationName: '三姓橋'},
        {stationNumber: '1230', stationName: '香山'},
        {stationNumber: '1240', stationName: '崎頂'},
        {stationNumber: '1250', stationName: '竹南'},
        {stationNumber: '2110', stationName: '談文'},
        {stationNumber: '2120', stationName: '大山'},
        {stationNumber: '2130', stationName: '後龍'},
        {stationNumber: '2140', stationName: '龍港'},
        {stationNumber: '2150', stationName: '白沙屯'},
        {stationNumber: '2160', stationName: '新埔'},
        {stationNumber: '2170', stationName: '通霄'},
        {stationNumber: '2180', stationName: '苑裡'},
        {stationNumber: '2190', stationName: '日南'},
        {stationNumber: '2200', stationName: '大甲'},
        {stationNumber: '2210', stationName: '臺中港'},
        {stationNumber: '2220', stationName: '清水'},
        {stationNumber: '2230', stationName: '沙鹿'},
        {stationNumber: '2240', stationName: '龍井'},
        {stationNumber: '2250', stationName: '大肚'},
        {stationNumber: '2260', stationName: '追分'},
        {stationNumber: '3140', stationName: '造橋'},
        {stationNumber: '3150', stationName: '豐富'},
        {stationNumber: '3160', stationName: '苗栗'},
        {stationNumber: '3170', stationName: '南勢'},
        {stationNumber: '3180', stationName: '銅鑼'},
        {stationNumber: '3190', stationName: '三義'},
        {stationNumber: '3210', stationName: '泰安'},
        {stationNumber: '3220', stationName: '后里'},
        {stationNumber: '3230', stationName: '豐原'},
        {stationNumber: '3240', stationName: '栗林'},
        {stationNumber: '3250', stationName: '潭子'},
        {stationNumber: '3260', stationName: '頭家厝'},
        {stationNumber: '3270', stationName: '松竹'},
        {stationNumber: '3280', stationName: '太原'},
        {stationNumber: '3290', stationName: '精武'},
        {stationNumber: '3300', stationName: '臺中'},
        {stationNumber: '3310', stationName: '五權'},
        {stationNumber: '3320', stationName: '大慶'},
        {stationNumber: '3330', stationName: '烏日'},
        {stationNumber: '3340', stationName: '新烏日'},
        {stationNumber: '3350', stationName: '成功'},
        {stationNumber: '3360', stationName: '彰化'},
        {stationNumber: '3370', stationName: '花壇'},
        {stationNumber: '3380', stationName: '大村'},
        {stationNumber: '3390', stationName: '員林'},
        {stationNumber: '3400', stationName: '永靖'},
        {stationNumber: '3410', stationName: '社頭'},
        {stationNumber: '3420', stationName: '田中'},
        {stationNumber: '3430', stationName: '二水'},
        {stationNumber: '3431', stationName: '源泉'},
        {stationNumber: '3432', stationName: '濁水'},
        {stationNumber: '3433', stationName: '龍泉'},
        {stationNumber: '3434', stationName: '集集'},
        {stationNumber: '3435', stationName: '水里'},
        {stationNumber: '3436', stationName: '車埕'},
        {stationNumber: '3450', stationName: '林內'},
        {stationNumber: '3460', stationName: '石榴'},
        {stationNumber: '3470', stationName: '斗六'},
        {stationNumber: '3480', stationName: '斗南'},
        {stationNumber: '3490', stationName: '石龜'},
        {stationNumber: '4050', stationName: '大林'},
        {stationNumber: '4060', stationName: '民雄'},
        {stationNumber: '4070', stationName: '嘉北'},
        {stationNumber: '4080', stationName: '嘉義'},
        {stationNumber: '4090', stationName: '水上'},
        {stationNumber: '4100', stationName: '南靖'},
        {stationNumber: '4110', stationName: '後壁'},
        {stationNumber: '4120', stationName: '新營'},
        {stationNumber: '4130', stationName: '柳營'},
        {stationNumber: '4140', stationName: '林鳳營'},
        {stationNumber: '4150', stationName: '隆田'},
        {stationNumber: '4160', stationName: '拔林'},
        {stationNumber: '4170', stationName: '善化'},
        {stationNumber: '4180', stationName: '南科'},
        {stationNumber: '4190', stationName: '新市'},
        {stationNumber: '4200', stationName: '永康'},
        {stationNumber: '4210', stationName: '大橋'},
        {stationNumber: '4220', stationName: '臺南'},
        {stationNumber: '4250', stationName: '保安'},
        {stationNumber: '4260', stationName: '仁德'},
        {stationNumber: '4270', stationName: '中洲'},
        {stationNumber: '4271', stationName: '長榮大學'},
        {stationNumber: '4272', stationName: '沙崙'},
        {stationNumber: '4290', stationName: '大湖'},
        {stationNumber: '4300', stationName: '路竹'},
        {stationNumber: '4310', stationName: '岡山'},
        {stationNumber: '4320', stationName: '橋頭'},
        {stationNumber: '4330', stationName: '楠梓'},
        {stationNumber: '4340', stationName: '新左營'},
        {stationNumber: '4350', stationName: '左營'},
        {stationNumber: '4360', stationName: '內惟'},
        {stationNumber: '4370', stationName: '美術館'},
        {stationNumber: '4380', stationName: '鼓山'},
        {stationNumber: '4390', stationName: '三塊厝'},
        {stationNumber: '4410', stationName: '民族'},
        {stationNumber: '4420', stationName: '科工館'},
        {stationNumber: '4430', stationName: '正義'},
        {stationNumber: '4440', stationName: '鳳山'},
        {stationNumber: '4450', stationName: '後庄'},
        {stationNumber: '4460', stationName: '九曲堂'},
        {stationNumber: '4470', stationName: '六塊厝'},
        {stationNumber: '5000', stationName: '屏東'},
        {stationNumber: '5010', stationName: '歸來'},
        {stationNumber: '5020', stationName: '麟洛'},
        {stationNumber: '5030', stationName: '西勢'},
        {stationNumber: '5040', stationName: '竹田'},
        {stationNumber: '5050', stationName: '潮州'},
        {stationNumber: '5060', stationName: '崁頂'},
        {stationNumber: '5070', stationName: '南州'},
        {stationNumber: '5080', stationName: '鎮安'},
        {stationNumber: '5090', stationName: '林邊'},
        {stationNumber: '5100', stationName: '佳冬'},
        {stationNumber: '5110', stationName: '東海'},
        {stationNumber: '5120', stationName: '枋寮'},
        {stationNumber: '5130', stationName: '加祿'},
        {stationNumber: '5140', stationName: '內獅'},
        {stationNumber: '5160', stationName: '枋山'},
        {stationNumber: '5190', stationName: '大武'},
        {stationNumber: '5200', stationName: '瀧溪'},
        {stationNumber: '5210', stationName: '金崙'},
        {stationNumber: '5220', stationName: '太麻里'},
        {stationNumber: '5230', stationName: '知本'},
        {stationNumber: '5240', stationName: '康樂'},
        {stationNumber: '5999', stationName: '潮州基地'},
        {stationNumber: '6000', stationName: '臺東'},
        {stationNumber: '6010', stationName: '山里'},
        {stationNumber: '6020', stationName: '鹿野'},
        {stationNumber: '6030', stationName: '瑞源'},
        {stationNumber: '6040', stationName: '瑞和'},
        {stationNumber: '6050', stationName: '關山'},
        {stationNumber: '6060', stationName: '海端'},
        {stationNumber: '6070', stationName: '池上'},
        {stationNumber: '6080', stationName: '富里'},
        {stationNumber: '6090', stationName: '東竹'},
        {stationNumber: '6100', stationName: '東里'},
        {stationNumber: '6110', stationName: '玉里'},
        {stationNumber: '6120', stationName: '三民'},
        {stationNumber: '6130', stationName: '瑞穗'},
        {stationNumber: '6140', stationName: '富源'},
        {stationNumber: '6150', stationName: '大富'},
        {stationNumber: '6160', stationName: '光復'},
        {stationNumber: '6170', stationName: '萬榮'},
        {stationNumber: '6180', stationName: '鳳林'},
        {stationNumber: '6190', stationName: '南平'},
        {stationNumber: '6200', stationName: '林榮新光'},
        {stationNumber: '6210', stationName: '豐田'},
        {stationNumber: '6220', stationName: '壽豐'},
        {stationNumber: '6230', stationName: '平和'},
        {stationNumber: '6240', stationName: '志學'},
        {stationNumber: '6250', stationName: '吉安'},
        {stationNumber: '7000', stationName: '花蓮'},
        {stationNumber: '7010', stationName: '北埔'},
        {stationNumber: '7020', stationName: '景美'},
        {stationNumber: '7030', stationName: '新城'},
        {stationNumber: '7040', stationName: '崇德'},
        {stationNumber: '7050', stationName: '和仁'},
        {stationNumber: '7060', stationName: '和平'},
        {stationNumber: '7070', stationName: '漢本'},
        {stationNumber: '7080', stationName: '武塔'},
        {stationNumber: '7090', stationName: '南澳'},
        {stationNumber: '7100', stationName: '東澳'},
        {stationNumber: '7110', stationName: '永樂'},
        {stationNumber: '7120', stationName: '蘇澳'},
        {stationNumber: '7130', stationName: '蘇澳新'},
        {stationNumber: '7140', stationName: '新馬'},
        {stationNumber: '7150', stationName: '冬山'},
        {stationNumber: '7160', stationName: '羅東'}
    ]
}

let vm = new Vue({
    el:'#app',
    data:data
});


$('.close').click(function(){
    $('.listView').slideToggle();
    $('.listView ul').html("");
});

$('.tripContent span').click(function(){
    var x =$(this).index()+1;
    $('.tripContent span').eq(x).addClass('cur').siblings().removeClass('cur');
});

$('.infAll').click(function(){
    $('.listView ul li.carInf').css('display','flex');
});
$('.infSpeed1').click(function(){
    $('.listView ul li').hide();
    $('.listView ul li.speed1').css('display','flex');
});
$('.infSpeed3').click(function(){
    $('.listView ul li').hide();
    $('.listView ul li.speed3').css('display','flex');
});
$('.infSpeed4').click(function(){
    $('.listView ul li').hide();
    $('.listView ul li.speed4').css('display','flex');
});


